package aifiver

var PresetUnstable = map[Facet]int{
	FacetOpenFantasy:             3,
	FacetOpenAesthetics:          4,
	FacetOpenFeelings:            -3,
	FacetOpenAdventurousness:     4,
	FacetOpenIdeas:               -3,
	FacetOpenValues:              -10,
	FacetConsCompetence:          8,
	FacetConsOrder:               7,
	FacetConsDutifulness:         3,
	FacetConsAchievementStriving: 10,
	FacetConsSelfDicipline:       4,
	FacetConsCautiousness:        -4,
	FacetExtrWarmth:              0,
	FacetExtrGregariousness:      3,
	FacetExtrAssertiveness:       9,
	FacetExtrActivity:            5,
	FacetExtrExcitementSeeking:   3,
	FacetExtrPositiveEmotions:    -3,
	FacetAgreTrust:               -5,
	FacetAgreStraightforwardness: -4,
	FacetAgreAltruism:            -4,
	FacetAgreCompliance:          -10,
	FacetAgreModesty:             -10,
	FacetAgreTenderMindedness:    -6,
	FacetNeurAnxiety:             0,
	FacetNeurAngryHostility:      2,
	FacetNeurDepression:          -10,
	FacetNeurSelfConciousness:    -10,
	FacetNeurImpulsiveness:       6,
	FacetNeurVulnerability:       -5,
}

var PresetFool = map[Facet]int{
	FacetOpenFantasy:             8,
	FacetOpenAesthetics:          4,
	FacetOpenFeelings:            6,
	FacetOpenAdventurousness:     4,
	FacetOpenIdeas:               7,
	FacetOpenValues:              6,
	FacetConsCompetence:          0,
	FacetConsOrder:               2,
	FacetConsDutifulness:         -3,
	FacetConsAchievementStriving: -1,
	FacetConsSelfDicipline:       -5,
	FacetConsCautiousness:        -7,
	FacetExtrWarmth:              7,
	FacetExtrGregariousness:      8,
	FacetExtrAssertiveness:       -2,
	FacetExtrActivity:            5,
	FacetExtrExcitementSeeking:   3,
	FacetExtrPositiveEmotions:    7,
	FacetAgreTrust:               8,
	FacetAgreStraightforwardness: -3,
	FacetAgreAltruism:            5,
	FacetAgreCompliance:          8,
	FacetAgreModesty:             6,
	FacetAgreTenderMindedness:    5,
	FacetNeurAnxiety:             3,
	FacetNeurAngryHostility:      -5,
	FacetNeurDepression:          -2,
	FacetNeurSelfConciousness:    5,
	FacetNeurImpulsiveness:       5,
	FacetNeurVulnerability:       4,
}
